### ISSUE TITLE
The maven dependency is extremely heavy

### ISSUE THREAD

**Issue by vivekkothari** [code-monastery/dropwizard-rabbitmq#1]
Hi,

I want to use this, but the maven dependency I am pulling is almost 14MB. Dropwizard dependency should be provided scope, also shade plugin should not be used.

**Comment by randyp** [comment]
Resolved in recent release [0.9.2.1](https://github.com/code-monastery/dropwizard-rabbitmq/releases/tag/dropwizard-rabbitmq-0.9.2.1).

Cheers!
