### ISSUE TITLE
Use DropWizard Duration in configuration class?

### ISSUE THREAD

**Issue by pkwarren** [code-monastery/dropwizard-rabbitmq#3]
Currently, the DropWizard RabbitMQ bundle exposes the following settings:

* heartbeat - Integer in seconds.
* connection timeout - Integer in milliseconds.
* handshake timeout - Integer in milliseconds.
* shutdown timeout - Integer in milliseconds.
* network recovery interval - Long in milliseconds.

This could potentially lead to confusion when configuring the bundle, and this is perhaps something that use of DropWizard's built-in [Duration class](https://github.com/dropwizard/dropwizard/blob/93efb8013e05664587deca34fecfbc2f00a42b92/dropwizard-util/src/main/java/io/dropwizard/util/Duration.java) could make for a more readable configuration. To preserve backwards compatibility, perhaps new setters for these properties could be changed to accept strings, and if no suffix is specified they preserve the current time units for each property.

**Comment by randyp** [comment]
I agree, sounds good.

**Comment by randyp** [comment]
@pkwarren How do you feel about changes in: a144e36c3a40d3b08573aecde3660fef1b473dea

Do you feel this issue is resolved with that change?

**Comment by randyp** [comment]
Also, I opted to not make worry about backwards compatibility. Rather, I need to add some upgrade notes somewhere.

**Comment by pkwarren** [comment]
@randyp - The change looks great! One small comment on use of https://docs.oracle.com/javase/8/docs/api/java/lang/Math.html#toIntExact-long- but otherwise this would be a nice addition. Thanks for the quick turnaround.

**Comment by randyp** [comment]
@pkwarren Instead of throwing a overflow exception, maybe we should use the MaxDuration class so that we get configuration validation errors?

**Comment by pkwarren** [comment]
Even better - 👍.

**Comment by randyp** [comment]
I am going to close this issue, reopen if necessary.
